name: CI
on:
  pull_request:
    types:
      - review_requested
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: npx eslint src --ext .ts,.tsx
